src/03.Presentation/App.EndPoints.RazorPages.HWW20/Pages/OperatorAgg/ListAppointmentsRequest.cshtml.cs
using App.Domain.Core._common.InMemory;
using App.Domain.Core.AppointmentRequestAgg.Contracts.AppService;
using App.Domain.Core.AppointmentRequestAgg.Dtos;
using App.Domain.Core.AppointmentRequestAgg.Enums;
using App.Domain.Core.CarModelAgg.Enums;
using App.EndPoints.RazorPages.HWW20.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace App.EndPoints.RazorPages.HWW20.Pages.OperatorAgg
{//
    public class ListAppointmentsRequestModel(IAppointmentRequestAppService appointmentRequestAppService) : PageModel
    {
        public List<AppointmentRequestSummaryDto> AppointmentRequestSummaryDto { get; set; }

        [BindProperty]
        public ChangeStatusInfoDto ChangeStatusInfoDto { get; set; }
        public void OnGet(string fromDate, string toDate, CompanyEnum? company)
        {
            var filter = new AppointmentFilterDto();
            if (!string.IsNullOrEmpty(fromDate))
                filter.FromDate = DateHelper.ShamsiToMiladi(fromDate);

            if (!string.IsNullOrEmpty(toDate))
                filter.ToDate = DateHelper.ShamsiToMiladi(toDate);

            filter.CompanyEnum = company;

            AppointmentRequestSummaryDto = appointmentRequestAppService.GetFiltered(filter);

            foreach (var item in AppointmentRequestSummaryDto)
                item.RequestDateShamsi = DateHelper.MiladiToShamsi(item.RequestDate);
        }

        public IActionResult OnPostAccept(int id)
        {
            ChangeStatusInfoDto = new ChangeStatusInfoDto
            {
                RequestId = id,
                NewStatusEnum = RequestStatusEnum.Approved,
                OperatorId = LocalStorage.Operator!.Id
            };
            appointmentRequestAppService.ChangeStatus(ChangeStatusInfoDto);
            return RedirectToPage();
        }

        public IActionResult OnPostReject(int id)
        {
            ChangeStatusInfoDto = new ChangeStatusInfoDto
            {
                RequestId = id,
                NewStatusEnum = RequestStatusEnum.Rejected,
                OperatorId = LocalStorage.Operator!.Id
            };
            appointmentRequestAppService.ChangeStatus(ChangeStatusInfoDto);
            return RedirectToPage();
        }
    }
}

src/03.Presentation/App.EndPoints.RazorPages.HWW20/Pages/OperatorAgg/Login.cshtml.cs
using App.Domain.Core._common.InMemory;
using App.Domain.Core.OperatorAgg.Contracts.AppService;
using App.Domain.Core.OperatorAgg.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace App.EndPoints.RazorPages.HWW20.Pages.OperatorAgg
{
    public class LoginModel(IOperatorAppService operatorAppService) : PageModel
    {
        [BindProperty]
        public LogInInfoDto LogInInfoDto { get; set; }
        public void OnGet()
        {
          
        }
        public IActionResult OnPost() 
        {
            try
            {
               int result=operatorAppService.Login(LogInInfoDto.Username, LogInInfoDto.Password);
                if (result>0)
                {
                    var operatorLogin=operatorAppService.GetByUsername(LogInInfoDto.Username);
                    LocalStorage.Operator = operatorLogin;
                    return RedirectToPage("ListAppointmentsRequest");
                }
                else 
                {
                    TempData["ErrorMessage"] = "درخواست شما به دلیل عدم تطابق قوانین رد شد.";
                    return Page();
                }
            }
            catch (Exception ex) 
            {
                TempData["ErrorMessage"] = ex.Message;
                return Page();
            }

        }
    }
}

src/03.Presentation/App.EndPoints.RazorPages.HWW20/Pages/OperatorAgg/ListAppointmentsRequest.cshtml
@page
@model App.EndPoints.RazorPages.HWW20.Pages.OperatorAgg.ListAppointmentsRequestModel
@{
}
@section Styles {
    <link rel="stylesheet" href="~/css/requests.css" />
}

<h1>لیست درخواست ها </h1>

<form >
    از تاریخ (شمسی):
    <input type="text" name="FromDate" placeholder="مثال: 1403/11/05" />

    تا تاریخ (شمسی):
    <input type="text" name="ToDate" placeholder="مثال: 1403/11/20" />

    <select name="Company">
        <option value="">همه</option>
        <option value="2">ایران خودرو</option>
        <option value="1">سایپا</option>
      
    </select>

    <button type="submit">فیلتر</button>
</form>



<table>

    <tr>
        <th>نام مالک</th>
        <th> پلاک</th>
        <th> نام مدل</th>
        <th> نام کارخانه</th>
        <th> تاریخ درخواست</th>
        <th>وضعیت </th>
    </tr>
    @foreach (var request in Model.AppointmentRequestSummaryDto)
    {
        <tr>

            <td>@request.OwnerName</td>
            <td>@request.LicensePlate</td>
            <td>@request.CarModelName</td>
            <td>@request.Company</td>
            <td>@request.RequestDateShamsi</td>
            <td>
                @request.Status
            </td>
            <td>
                <form method="post" asp-page-handler="Accept" asp-route-id="@request.Id" style="display:inline">
                    <button type="submit" class="accept">پذیرش</button>
                </form>

                <form method="post" asp-page-handler="Reject" asp-route-id="@request.Id" style="display:inline">
                    <button type="submit" class="reject">رد</button>
                </form>

            </td>


        </tr>

    }

</table>

src/03.Presentation/App.EndPoints.RazorPages.HWW20/Pages/OperatorAgg/Login.cshtml
@page
@model App.EndPoints.RazorPages.HWW20.Pages.OperatorAgg.LoginModel
@{
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}
<h1>صفحه لاگین</h1>
<form method="post">

   <div>
      <label asp-for="LogInInfoDto.Username">نام کاربری</label>
      <input asp-for="LogInInfoDto.Username" type="text" required />
  </div>
   <div>
      <label asp-for="LogInInfoDto.Password">رمز عبور</label>
      <input asp-for="LogInInfoDto.Password" type="text" required />
  </div>
  <div>
      <button type="submit" >ورود</button>
  </div>

</form>